export const AppImage = {
  bg: require("./bg.png"),
  logo: require("./logo.svg"),
  menu: require("./menu.svg"),
  closeIcon: require("./x-close.svg"),
  home1: require("./home1.png"),
  home2: require("./home2.png"),
  home3: require("./home3.png"),
  chip: require("./chip.svg"),
  cude: require("./cude.svg"),
  percentage: require("./percentage.svg"),
  server: require("./server.svg"),
  target: require("./target.svg"),
  users: require("./users.svg"),
  aboutCircle: require("./aboutCircle.png"),
  aboutBg: require("./aboutBg.png"),
  shield: require("./shield.svg"),
  dataflow: require("./dataflow.svg"),
  barChart: require("./barChart.svg"),
}